# Script to convert casacore images generated by the AARTFAAC pipeline to FITS.
# NOTE: Uses CASA environment. First start casa, then: 
# CASA>> execfile ('casa2fits.py')
# pep/10Jun12

import glob;
import os;

print 'Generating FITS files from all CASAcore images in current folder';
default (exportfits)
 
os.system ('mkdir fits');
# for image_file in glob.glob(os.path.join('fits/','*.fits')):
for imagename in glob.glob('*.image'):
	fitsimage = 'fits/' + imagename + '.fits';
	print 'Converting file ', imagename, ' to ', fitsimage;
	exportfits();
	print 'Done';

