% Script to generate a timeseries of the autocorrelations of each antenna in 
% a provided ACM. Works on the .bin format generated by readms2float.m
% pep/09Jul13
%  Arguments:
%	 fname : Filename of the ACM timeseries
% 	 offset: Timeslice offset from which to start
%   ntimes : Number of timeslices on which to operate. -1 => all available
% Returns:
%	times : Vector containing times in MJD.
% autocorr: 288xntimes matrix contaning the autocorrelations

function [times, autocorr] = genautocorr (fname, offset, ntimes)
	if isempty(fname)
		error ('Usage: genautocorr filename.bin timeoffset ntimeslices');
	end;

	fid = fopen (fname, 'rb');
 	if ntimes == -1
		[ntimes, tmin, tmax, dt] = getnrecs (fname);
	end;

	autocorr = zeros (288, ntimes);
	times = zeros (ntimes);

	for ind = 1:ntimes
		[acc, times(ind), freq] = readms2float (fid, -1, -1, 288);
		autocorr (:, ind) = diag (acc);
	end;
