% Script to read images generated by wrimg2bin.m.
% pep/28Jan13

% Arguments:
%	fid   		: file id of image binary file.

% Returns:
%  img.tobs		: Time of image, MJD sec.
%  img.freq		: Frequency of image, Hz.
%  img.pix2laxis: Length of l-axis of image.
%  img.l 		: l-axis of image
%  img.pix2maxis: Length of m-axis of image.
%  img.m 		: m-axis of image
%  img.map 		: pix2laxis X pix2maxis float matrix of pixel values.
function [img] = rdimg2bin (fid)
	if (fid < 0)
		disp ('rdimg2bin: Inconsistent file id. Quitting.');
		return;
	end;

	img.tobs      = fread (fid, 'double');
	img.freq      = fread (fid, 'double');
	img.pix2laxis = fread (fid, 'float32');
	img.l         = fread (fid, img.pix2laxis, 'float32');
	img.pix2maxis = fread (fid, 'float32');
	img.m         = fread (fid, img.pix2maxis, 'float32');
	img.map       = fread (fid, img.pix2laxis*img.pix2maxis, 'float32');
