% Script to read in a calibration solution record, as generated by
% wrcalvis2bin.m
% pep/20Jan13
function [rec] = readcalsol (fid)
	if (fid < 0)
		disp ('File not readable! Quitting!');
		return;
	end;

	rec.tobs = fread (fid, 1, 'double');	
	if (isempty(rec.tobs) == 1) 
		disp('readcalsol: End of file reached!'); 
		err = MException('readcalsol:EoF', 'EoF reached!');
		throw (err);
		return ;
	end;

	% NOTE: By default, Matlab creates double instances, so record sizes can be
	% off!
	rec.freq 		 = fread (fid, 1, 'double');	
	rec.numflagants  = single(fread (fid, 1, 'float32'));
	rec.flagants     = single(fread (fid, rec.numflagants, 'float32'));
	rec.gainsol_len  = single(fread (fid, 1, 'float32'));
	rec.real_gainsol = single(fread (fid, rec.gainsol_len, 'float32'));
	rec.imag_gainsol = single(fread (fid, rec.gainsol_len, 'float32'));
	rec.calext_iters = single(fread (fid, 1, 'float32'));
	rec.pinv_sol     = single(fread (fid, 1, 'float32'));
	rec.stefcal_iters= single(fread (fid, 1, 'float32'));
	rec.stefcal_tol  = single(fread (fid, 1, 'float32'));
	rec.calsrcs 	 = single(fread (fid, 1, 'float32'));
	rec.sigmas  	 = single(fread (fid, rec.calsrcs, 'float32')); 
	rec.poslen  	 = single(fread (fid, 1, 'float32'));
	rec.thsrc_cat  = single(fread (fid, rec.poslen, 'float32'));
	rec.phisrc_cat = single(fread (fid, rec.poslen, 'float32'));
	rec.thsrc_wsf  = single(fread (fid, rec.poslen, 'float32'));
	rec.phisrc_wsf = single(fread (fid, rec.poslen, 'float32'));
	rec.sigmanlen  = single(fread (fid, 1, 'float32'));
	rec.real_sigman= single(fread (fid, rec.sigmanlen, 'float32'));
	rec.imag_sigman= single(fread (fid, rec.sigmanlen, 'float32'));
	return;
