% Script to return a chosen timeslice from a .bin file generated by ms2float.py
% Either an offset, or an absolute time can be given, with the function 
% returning the ACM, MJD time (in secs), Freq (in Hz).
% NOTE: If recoffset=-1, implies return the next record, for any other 
% positive number, return the record with that number offset from beginning
% of file.
% pep/01May12
% function [acc, tobs, freqobs] = readms2float (filename, recoffset, rettime)
function [acc, tobs, freqobs] = readms2float (fid, recoffset, rettime)
	Nelem = 288; 
	nblines = Nelem * (Nelem + 1)/2; 
	tobs = 1; freqobs = 1;
	recsize = 8*(2+nblines); % Bytes, assumed double =8, float=4 bytes.
	% fid = fopen (filename, 'rb');

	% NOTE: Currently ms2float handles only one channel data
	if (recoffset > 0)
		fseek (fid, (recoffset-1)*recsize, 'bof');
%		for recs = 1:recoffset
		  tobs = fread (fid, 1, 'double');
	          freqobs = fread (fid, 1, 'double');
		  a  = fread (fid, 2*nblines, 'float'); % Read one ccm worth
%		end
		disp (['Time at offset ', num2str(recoffset), ' recs: ', num2str(tobs)]);
	% end
	elseif (recoffset == -1) % Return next record
		tobs = fread (fid, 1, 'double');
	        freqobs = fread (fid, 1, 'double');
		a  = fread (fid, 2*nblines, 'float'); % Read one ccm worth
		% disp (['Time: ', num2str(tobs), ' Freq: ', num2str(freqobs)]);
	end	

%	else if (recoffset < 0 && rettime > 0)
%		tobs1 = fread (fid, 1, 'double');
%	        freqobs = fread (fid, 1, 'double');
%		a = fread (fid, 2*nblines, 'float'); % Read one ccm worth
%		tobs2 = fread (fid, 1, 'double');
%		dt = tobs2 - tobs1;			
%		recs2time = int32 ((rettime - tobs1)/dt);
%		fseek (fid, 0, -1);
%		for recs = 1:recs2time
%		  tobs = fread (fid, 1, 'double');
%	          freqobs = fread (fid, 1, 'double');
%		  a = fread (fid, 2*nblines, 'float'); % Read one ccm worth
%		end
%		tobs = fread (fid, 1, 'double');
%	        freqobs = fread (fid, 1, 'double');
%		a = fread (fid, 2*nblines, 'float'); % Read one ccm worth
%		disp (['Found closest time to ', num2str(rettime), ':', num2str(tobs), ' at offset:', num2str(recs2time)]);
%	end

        comp = complex (a(1:2:length(a)), a(2:2:length(a))); % to complex
        % create instantaneous ccm from vector
        acm = triu (ones (Nelem));
        acm (acm == 1) = comp;
        acc = acm + acm' - diag(diag(acm));
	%fclose (fid);
end
