% Script to read in a calibration solution record, as generated by
% wrcalvis2bin.m
% pep/20Jan13
% Arguments:
%  fid : file id of solution file
% Returns:
%  rec : calsol record.
function [rec] = readcalsol (fid)
	if (fid < 0)
		error ('File not readable! Quitting!');
	end;

	rec.tobs = fread (fid, 1, 'double');	
	if (isempty(rec.tobs) == 1) 
		error ('readcalsol: End of file reached!'); 
		err = MException('readcalsol:EoF', 'EoF reached!');
		throw (err);
		return ;
	end;

	% NOTE: By default, Matlab creates double instances, so record sizes can be
	% off!
	rec.freq 		 = fread (fid, 1, 'double');	
	rec.numflagants  = single(fread (fid, 1, 'float32'));
	rec.flagant     = single(fread (fid, rec.numflagants, 'float32'));
	rec.gainsol_len  = single(fread (fid, 1, 'float32'));
	% Deprecated, should go in favour of rec.gainsol.
%	rec.real_gainsol = single(fread (fid, rec.gainsol_len, 'float32'));
%	rec.imag_gainsol = single(fread (fid, rec.gainsol_len, 'float32'));
%	rec.gainsol = complex (rec.real_gainsol, rec.imag_gainsol);
	real_gainsol = single(fread (fid, rec.gainsol_len, 'float32'));
	imag_gainsol = single(fread (fid, rec.gainsol_len, 'float32'));
	rec.gainsol = complex (real_gainsol, imag_gainsol);
	rec.calext_iters = single(fread (fid, 1, 'float32'));
	rec.pinv_sol     = single(fread (fid, 1, 'float32'));
	rec.stefcal_iters= single(fread (fid, 1, 'float32'));
	rec.stefcal_tol  = single(fread (fid, 1, 'float32'));
	rec.calsrcs 	 = single(fread (fid, 1, 'float32'));
	rec.sigmas  	 = single(fread (fid, rec.calsrcs, 'float32')); 
	rec.poslen  	 = single(fread (fid, 1, 'float32'));
	rec.thsrc_cat    = single(fread (fid, rec.poslen, 'float32'));
	rec.phisrc_cat   = single(fread (fid, rec.poslen, 'float32'));
	rec.thsrc_wsf    = single(fread (fid, rec.poslen, 'float32'));
	rec.phisrc_wsf   = single(fread (fid, rec.poslen, 'float32'));
	rec.sigmanlen    = single(fread (fid, 1, 'float32'));
	remants = length (real_gainsol) - length (rec.flagant);
	% Deprecated, should go in favour of rec.sigman
%	rec.real_sigman  = single(fread (fid, rec.sigmanlen, 'float32'));
%	rec.imag_sigman  = single(fread (fid, rec.sigmanlen, 'float32'));
%	rec.sigman = reshape (complex (rec.real_sigman, rec.imag_sigman), ... 
	real_sigman  = single(fread (fid, rec.sigmanlen, 'float32'));
	imag_sigman  = single(fread (fid, rec.sigmanlen, 'float32'));
	rec.sigman = reshape (complex (real_sigman, imag_sigman), ... 
							[remants, remants]);
	return;
