% Script to display images stored in .bin files, as generated by wrimg2bin.m
% pep/28Jan13

% Arguments:
%	fname  : image binary file name
%	nrecs  : Number of images to show. -1 => show all images.

function showbinimages (fname, nrecs)
	fid = fopen (fname, 'rb');
	if (fid < 0)
		disp ('showbinimages: fid < 0! Quitting.');
		return;
	end;

	img = readimg2bin (fid);
	map = reshape (img.map, img.pix2laxis, img.pix2maxis);
    mask = NaN(size (map));
    mask(meshgrid(img.l).^2 + meshgrid(img.m).'.^2 < 1) = 1;
	disp (sprintf ('Obs   info: Time: %f, freq: %f', img.tobs, img.freq));

	disp (sprintf ('Image info: %fX%f, %f<l<%f, %f<m<%f', img.pix2laxis, ...
		  img.pix2maxis, min(img.l), max(img.l), min(img.m), max(img.m)));

	if (nrecs < 0)
		fdir = dir (fname);
		filesize = fdir.bytes;
		imgwhos = whos ('img');
		imgsize = imgwhos.bytes;
		nrecs = filesize/imgsize;
	end;

	figure;

	for im = 1:nrecs
		img = readimg2bin (fid);
		map = reshape (img.map, img.pix2laxis, img.pix2maxis);
    	disp (sprintf('Showing image %03d of %03d, Time: %.2f', im, nrecs, ...
			  (img.tobs)));
    	imagesc(img.l, img.m, map .* mask);
    
    
    	set(gca, 'FontSize', 16);
    	title (sprintf ('Time: %f, freq: %f', img.tobs, img.freq));
	    axis equal
   		axis tight
   		set (gca, 'YDir', 'Normal'); % To match orientation with station images
   		set (gca, 'XDir', 'Reverse'); % To match orientation with station images

    	ylabel('South \leftarrow m \rightarrow North');
    	xlabel('East \leftarrow l \rightarrow West');
    
    
    	set(colorbar, 'FontSize', 16);
    	pause (0.5);
	end;

	 
