% Script to plot lightcurves obtained for flux calibration purposes
% pep/20Nov15

% Source files:
calsrc = containers.Map();
srcnames = {'3C11', '3C380', '3C415',  '3C430',  '3C48',  
'3C147',  '3C409',  '3C426',  '3C433',  '4C55'};

cat = load ('srclist3CR.mat');
srcra = containers.Map(srcnames,{cat

prefix='trap_vloSB003_cendes_dataset15/';

% NOTE: Format is of the csv file as generated by the monitoring list lightcurve on Banana.
fmt = '%d %s %f %f %f %f %f %f %d %f %f';

fid = fopen ([prefix, srcnames{1}, '.txt']);
dat = textscan (fid, fmt, 'Delimiter', ',', 'HeaderLines', 1);

% Determine the elevation of the source from the source coordinates.
