% Script to plot lightcurves obtained for flux calibration purposes
% Based on the output of TraP runs on calibrator sources. Still TODO.
% pep/20Nov15

% Source files:
% Map between source names and offsets in 3CR catalog.
calsrc = containers.Map({'3C11', '3C380', '3C415',  '3C430',  '3C48',  
'3C147',  '3C409',  '3C426',  '3C433',  '4C55'}, {;

cat = load ('srclist3CR.mat');
srcra = containers.Map(srcnames,{cat

prefix='trap_vloSB003_cendes_dataset15/';

% NOTE: Format is of the csv file as generated by the monitoring list lightcurve on Banana.
fmt = '%d %s %f %f %f %f %f %f %d %f %f';

fid = fopen ([prefix, srcnames{1}, '.txt']);
dat = textscan (fid, fmt, 'Delimiter', ',', 'HeaderLines', 1);

<<<<<<< HEAD
% Determine the elevation of the source from the source coordinates and the time
% of observation.


=======
% Determine the elevation of the source from the source coordinates.

% Plot rms flux vs. elevation, to see if higher elevation has lower noise.
% NOTE that after beam model correction, the noise is expected to be higher...


% Plot scatter plot of correlations of one source with another (scatter matrix)
% This is to check if source variations are correlated, which can point to a 
% calibration issue.

% Plot source trace against beam model (Do this only on data without beam
% correction?) 
>>>>>>> 05e28339196f92e05a3f00f447d32f07cbb8b9be
